plugin: aws_ec2

aws_access_key: AKIAUWNW4RE6G3QTPASC
aws_secret_key: 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

regions:
  - ap-southeast-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
